/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswersCollected: typeof import('./components/AnswersCollected.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    LoadingComponent: typeof import('./components/LoadingComponent.vue')['default']
    QuizQuestion: typeof import('./components/QuizQuestion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollFiller: typeof import('./components/ScrollFiller.vue')['default']
  }
}
